import { createContext, useContext, useState, ReactNode, useEffect } from 'react';

export type Language = 'de' | 'en' | 'hi';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  de: {
    // ===== NAVIGATION & SIDEBAR =====
    'nav.dashboard': 'Dashboard',
    'nav.guestManagement': 'Gästeverwaltung',
    'nav.departmentKpis': 'Abteilungs-KPIs',
    'nav.overview': 'Übersicht',
    'nav.kpiTrends': 'KPI-Trends',
    'nav.housekeeping': 'Housekeeping',
    'nav.kitchen': 'Küche',
    'nav.service': 'Service',
    'nav.frontoffice': 'Rezeption',
    'nav.spa': 'Spa',
    'nav.technical': 'Technik',
    'nav.admin': 'Verwaltung',
    'nav.personnelManagement': 'Personalmanagement',
    'nav.employees': 'Mitarbeiter',
    'nav.shiftPlanningAll': 'Schichtplanung (Alle)',
    'nav.departmentShiftPlan': 'Abteilungs-Schichtplan',
    'nav.timeAccounts': 'Zeitkonten',
    'nav.personnelKpis': 'Personal-KPIs',
    'nav.planningAlarms': 'Planung & Alarme',
    'nav.budgetPlanning': 'Budgetplanung',
    'nav.kpiAlarms': 'KPI-Alarme',
    'nav.departmentHeads': 'Abteilungsleiter',
    'nav.userManagement': 'Benutzerverwaltung',
    'nav.dataAnalysis': 'Daten & Analysen',
    'nav.dataImport': 'Datenimport',
    'nav.accountMaster': 'Kontenstamm',
    'nav.periodComparison': 'Periodenvergleich',
    'nav.areaAnalysis': 'Bereichsanalyse',
    'nav.dataQuality': 'Datenqualität',
    'nav.financialAnalysis': 'FinanzAnalyse',
    'nav.hotelBalanceLists': 'Hotel Saldenlisten',
    
    // ===== DASHBOARD =====
    'dashboard': 'Dashboard',
    'dashboard.description': 'Übersicht Ihrer Finanzkennzahlen',
    'dashboard.noData': 'Keine Daten vorhanden',
    'dashboard.uploadHint': 'Laden Sie Ihre Saldenlisten hoch, um die Finanzanalyse zu starten.',
    'dashboard.expectedFormat': 'Erwartetes Format',
    'dashboard.financialOverview': 'Finanzübersicht',
    
    // ===== KPI CARDS =====
    'kpi.totalRevenue': 'Gesamterlöse',
    'kpi.fbRevenue': 'F&B Erlöse',
    'kpi.totalExpenses': 'Gesamtaufwand',
    'kpi.personnelCosts': 'Personalkosten',
    'kpi.grossProfit': 'Rohertrag',
    'kpi.grossMargin': 'Rohmarge',
    'kpi.previousMonth': 'Vormonat',
    'kpi.previousYear': 'Vorjahr',
    'kpi.pm': 'VM',
    'kpi.py': 'VJ',
    
    // ===== TOOLTIPS =====
    'tooltip.revenue': 'Summe aller Erlös-Konten. Klicken für Aufschlüsselung nach Bereich.',
    'tooltip.fb': 'Erlöse aus Food & Beverage (Restaurant, Küche, Bar, Bankett). Klicken für Details.',
    'tooltip.expenses': 'Summe aller Aufwandskonten der Klassen 5-8. Klicken für Aufschlüsselung.',
    'tooltip.personnel': 'Summe aller Konten der Klasse 6 (Löhne, Gehälter, Sozialabgaben). Klicken für Aufschlüsselung.',
    'tooltip.grossProfit': 'Erlöse − Aufwand (Klassen 5-8). Klicken für Details.',
    'tooltip.grossMargin': 'Rohertrag ÷ Erlöse × 100 – zeigt die Rentabilität in Prozent',
    
    // ===== CHARTS =====
    'chart.expensesByClass': 'Gesamtaufwand nach Kontoklassen',
    'chart.revenueByArea': 'Erlöse nach Bereich',
    'chart.expensesByArea': 'Aufwand nach Bereich',
    'chart.materialExpenses': 'Materialaufwand',
    'chart.personnelExpenses': 'Personalaufwand',
    'chart.depreciation': 'Abschreibungen',
    'chart.otherExpenses': 'Sonstiger Aufwand',
    
    // ===== ALARM WIDGET =====
    'alarm.title': 'KPI-Alarme',
    'alarm.noThresholds': 'Keine Schwellenwerte konfiguriert',
    'alarm.allNormal': 'Alle KPIs im Normalbereich',
    'alarm.critical': 'kritisch',
    'alarm.warning': 'Warnung',
    'alarm.moreAlarms': 'weitere Alarme',
    
    // ===== BUDGET WIDGET =====
    'budget.deviations': 'Budget-Abweichungen (Soll-Ist)',
    'budget.noData': 'Keine Budgetdaten für diesen Monat vorhanden',
    'budget.revenue': 'Umsatz',
    'budget.personnel': 'Personal',
    
    // ===== UPLOAD VIEW =====
    'upload.title': 'Saldenlisten-Import',
    'upload.description': 'CSV-Dateien aus Ihrer Buchhaltung importieren',
    'upload.dropzone': 'Saldenlisten hier ablegen oder klicken',
    'upload.accepted': 'Akzeptiert: CSV, Excel',
    'upload.importedFiles': 'Importierte Dateien',
    'upload.noFiles': 'Noch keine Dateien importiert',
    'upload.accounts': 'Konten',
    'upload.deleteAll': 'Alle Daten löschen',
    'upload.confirmDelete': 'Alle importierten Daten werden unwiderruflich gelöscht.',
    'upload.success': 'Import erfolgreich',
    'upload.accountsImported': 'Konten importiert für',
    'upload.error': 'Importfehler',
    
    // ===== ACCOUNTS VIEW =====
    'accounts.title': 'Kontenstamm',
    'accounts.description': 'Übersicht aller Konten mit Zuordnungen',
    'accounts.accountNumber': 'Kontonummer',
    'accounts.description2': 'Bezeichnung',
    'accounts.class': 'Klasse',
    'accounts.area': 'Bereich',
    'accounts.type': 'Kostenarttyp',
    'accounts.kpiCategory': 'KPI-Kategorie',
    'accounts.currentBalance': 'Aktueller Saldo',
    'accounts.search': 'Konten durchsuchen...',
    'accounts.all': 'Alle',
    'accounts.totalAccounts': 'Konten gesamt',
    'accounts.withBalance': 'mit Saldo',
    
    
    // ===== DATA QUALITY VIEW =====
    'dataQuality.title': 'Datenqualität',
    'dataQuality.description': 'Analyse der Datenqualität und Vollständigkeit',
    'dataQuality.complete': 'Vollständig',
    'dataQuality.incomplete': 'Unvollständig',
    'dataQuality.missing': 'Fehlend',
    
    // ===== EMPLOYEES VIEW =====
    'employees.title': 'Mitarbeiter-Stammdaten',
    'employees.description': 'Übersicht aller Mitarbeiter',
    'employees.personnelNumber': 'Personalnr.',
    'employees.firstName': 'Vorname',
    'employees.lastName': 'Nachname',
    'employees.department': 'Abteilung',
    'employees.position': 'Position',
    'employees.employmentType': 'Anstellungsart',
    'employees.weeklyHours': 'Wochenstunden',
    'employees.hourlyRate': 'Stundenlohn',
    'employees.entryDate': 'Eintrittsdatum',
    'employees.status': 'Status',
    'employees.active': 'Aktiv',
    'employees.inactive': 'Inaktiv',
    'employees.addNew': 'Neuer Mitarbeiter',
    'employees.search': 'Mitarbeiter suchen...',
    'employees.total': 'Mitarbeiter gesamt',
    'employees.activeCount': 'aktiv',
    
    // ===== SHIFT PLANNING =====
    'shifts.title': 'Schichtplanung',
    'shifts.description': 'Wöchentliche Schichtplanung',
    'shifts.week': 'Woche',
    'shifts.employee': 'Mitarbeiter',
    'shifts.monday': 'Montag',
    'shifts.tuesday': 'Dienstag',
    'shifts.wednesday': 'Mittwoch',
    'shifts.thursday': 'Donnerstag',
    'shifts.friday': 'Freitag',
    'shifts.saturday': 'Samstag',
    'shifts.sunday': 'Sonntag',
    'shifts.work': 'Arbeit',
    'shifts.vacation': 'Urlaub',
    'shifts.sick': 'Krank',
    'shifts.training': 'Fortbildung',
    'shifts.free': 'Frei',
    'shifts.overtime': 'Überstundenabbau',
    'shifts.parentalLeave': 'Elternzeit',
    'shifts.other': 'Sonstiges',
    'shifts.plannedHours': 'Soll-Stunden',
    'shifts.actualHours': 'Ist-Stunden',
    'shifts.overtimeHours': 'Überstunden',
    'shifts.printView': 'Druckansicht',
    'shifts.pdfExport': 'PDF Export',
    'shifts.sendToHead': 'An Leiter senden',
    'shifts.selectDepartment': 'Abteilung wählen',
    'shifts.legend': 'Legende',
    'shifts.planningRate': 'Planungsquote',
    'shifts.sickDays': 'Krankheitstage',
    'shifts.vacationDays': 'Urlaubstage',
    'shifts.workDays': 'Arbeitstage',
    'shifts.summary': 'Zusammenfassung',
    
    // ===== TIME ACCOUNTS =====
    'timeAccounts.title': 'Zeitkonten',
    'timeAccounts.description': 'Überstunden- und Urlaubskonten',
    'timeAccounts.overtimeBalance': 'Überstunden-Saldo',
    'timeAccounts.vacationEntitlement': 'Urlaubsanspruch',
    'timeAccounts.vacationTaken': 'Urlaub genommen',
    'timeAccounts.vacationRemaining': 'Resturlaub',
    'timeAccounts.sickDays': 'Krankheitstage',
    
    // ===== BUDGET PLANNING =====
    'budgetPlanning.title': 'Budgetplanung',
    'budgetPlanning.description': 'Jahresbudgets und Soll-Ist-Vergleich',
    'budgetPlanning.budget': 'Budget',
    'budgetPlanning.actual': 'Ist',
    'budgetPlanning.deviation': 'Abweichung',
    'budgetPlanning.year': 'Jahr',
    'budgetPlanning.month': 'Monat',
    
    // ===== KPI ALARMS =====
    'kpiAlarms.title': 'KPI-Alarme & Schwellenwerte',
    'kpiAlarms.description': 'Konfiguration von Grenzwerten und Benachrichtigungen',
    'kpiAlarms.threshold': 'Schwellenwert',
    'kpiAlarms.min': 'Minimum',
    'kpiAlarms.max': 'Maximum',
    'kpiAlarms.alarmActive': 'Alarm aktiv',
    'kpiAlarms.addThreshold': 'Schwellenwert hinzufügen',
    
    // ===== DEPARTMENT HEADS =====
    'deptHeads.title': 'Abteilungsleiter',
    'deptHeads.description': 'Zuständige Führungskräfte nach Bereich',
    'deptHeads.name': 'Name',
    'deptHeads.email': 'E-Mail',
    'deptHeads.department': 'Abteilung',
    'deptHeads.active': 'Aktiv',
    
    // ===== USER MANAGEMENT =====
    'userMgmt.title': 'Benutzerverwaltung',
    'userMgmt.description': 'Benutzer und Berechtigungen verwalten',
    'userMgmt.user': 'Benutzer',
    'userMgmt.role': 'Rolle',
    'userMgmt.admin': 'Administrator',
    'userMgmt.deptHead': 'Abteilungsleiter',
    'userMgmt.employee': 'Mitarbeiter',
    'userMgmt.inviteUser': 'Benutzer einladen',
    
    // ===== GUEST MANAGEMENT =====
    'guests.title': 'Gästeverwaltung',
    'guests.description': 'Gästedaten und Aufenthalte',
    'guests.guestNumber': 'Gastnummer',
    'guests.name': 'Name',
    'guests.email': 'E-Mail',
    'guests.phone': 'Telefon',
    'guests.stays': 'Aufenthalte',
    'guests.totalRevenue': 'Gesamtumsatz',
    'guests.vip': 'VIP',
    'guests.addGuest': 'Neuer Gast',
    'guests.search': 'Gäste suchen...',
    
    // ===== COMMON =====
    'common.loading': 'Laden...',
    'common.save': 'Speichern',
    'common.cancel': 'Abbrechen',
    'common.delete': 'Löschen',
    'common.edit': 'Bearbeiten',
    'common.add': 'Hinzufügen',
    'common.search': 'Suchen',
    'common.filter': 'Filter',
    'common.export': 'Exportieren',
    'common.import': 'Importieren',
    'common.print': 'Drucken',
    'common.close': 'Schließen',
    'common.confirm': 'Bestätigen',
    'common.yes': 'Ja',
    'common.no': 'Nein',
    'common.actions': 'Aktionen',
    'common.status': 'Status',
    'common.date': 'Datum',
    'common.time': 'Zeit',
    'common.total': 'Gesamt',
    'common.details': 'Details',
    'common.back': 'Zurück',
    'common.next': 'Weiter',
    'common.previous': 'Vorherige',
    'common.handbook': 'Handbuch',
    'common.language': 'Sprache',
    'common.german': 'Deutsch',
    'common.english': 'English',
    'common.hindi': 'हिन्दी',
    'common.noData': 'Keine Daten vorhanden',
    'common.error': 'Fehler',
    'common.success': 'Erfolg',
    
    // ===== MONTHS =====
    'month.january': 'Januar',
    'month.february': 'Februar',
    'month.march': 'März',
    'month.april': 'April',
    'month.may': 'Mai',
    'month.june': 'Juni',
    'month.july': 'Juli',
    'month.august': 'August',
    'month.september': 'September',
    'month.october': 'Oktober',
    'month.november': 'November',
    'month.december': 'Dezember',
    
    // ===== DAYS =====
    'day.mon': 'Mo',
    'day.tue': 'Di',
    'day.wed': 'Mi',
    'day.thu': 'Do',
    'day.fri': 'Fr',
    'day.sat': 'Sa',
    'day.sun': 'So',
    
    // ===== DEPARTMENT KPIs =====
    'deptKpi.title': 'Abteilungs-KPIs',
    'deptKpi.description': 'Deckungsbeitragsrechnung nach Abteilung',
    'deptKpi.noData': 'Keine Daten vorhanden',
    'deptKpi.uploadHint': 'Laden Sie Ihre Saldenlisten hoch, um die Abteilungs-KPIs zu berechnen.',
    'deptKpi.yearComparison': 'Jahresvergleich',
    'deptKpi.vs': 'vs.',
    'deptKpi.operativeDepts': 'Operative Abteilungen',
    'deptKpi.clickForDetails': '(klicken für Kontendetails)',
    'deptKpi.serviceDepts': 'Service-Bereiche (Kostenübersicht)',
    'deptKpi.accountDetails': 'Kontendetails',
    'deptKpi.accountsWithBalance': 'Konten mit Saldo',
    'deptKpi.noAccountBalances': 'Keine Kontensalden für diesen Zeitraum',
    'deptKpi.totalRevenue': 'Gesamtumsatz',
    'deptKpi.cogs': 'Wareneinsatz',
    'deptKpi.db1Total': 'DB I gesamt',
    'deptKpi.personnel': 'Personal',
    'deptKpi.db2Total': 'DB II gesamt',
    'deptKpi.energy': 'Energie',
    'deptKpi.revenue': 'Umsatz',
    'deptKpi.db1': 'DB I',
    'deptKpi.db2': 'DB II',
    'deptKpi.operatingExpenses': 'Betriebsaufwand',
    'deptKpi.marketing': 'Marketing',
    'deptKpi.total': 'Gesamt',
    'deptKpi.vsLastYear': 'vs. Vorjahr',
    'deptKpi.py': 'VJ',
    'deptKpi.pyShort': 'VJ',
    'deptKpi.exportSuccess': 'KPI-Export erfolgreich erstellt',
    'deptKpi.revenueCurrent': 'Umsatz aktuell',
    'deptKpi.revenuePY': 'Umsatz Vorjahr',
    'deptKpi.db2Current': 'DB II aktuell',
    'deptKpi.db2PY': 'DB II Vorjahr',
    
    // ===== AREA ANALYSIS VIEW =====
    'areas.title': 'Bereichsanalyse',
    'areas.description': 'Aggregierte Werte nach Geschäftsbereich',
    'areas.noData': 'Keine Daten vorhanden. Bitte Saldenlisten hochladen.',
    'areas.revenueByArea': 'Erlöse nach Bereich',
    'areas.expensesByArea': 'Aufwand nach Bereich',
    'areas.noRevenueData': 'Keine Erlösdaten',
    'areas.noExpenseData': 'Keine Aufwanddaten',
    
    // ===== COMPARISON VIEW =====
    'comparison.title': 'Periodenvergleich',
    'comparison.description': 'Vergleich',
    'comparison.vsPMAndPY': 'vs. Vormonat & Vorjahr',
    'comparison.searchAccount': 'Konto suchen...',
    'comparison.allAreas': 'Alle Bereiche',
    'comparison.allTypes': 'Alle Typen',
    'comparison.revenue': 'Erlös',
    'comparison.expense': 'Einkauf',
    'comparison.account': 'Konto',
    'comparison.designation': 'Bezeichnung',
    'comparison.current': 'Aktuell',
    'comparison.prevMonth': 'Vormonat',
    'comparison.pmDiff': 'VM Δ',
    'comparison.prevYear': 'Vorjahr',
    'comparison.pyDiff': 'VJ Δ',
    'comparison.noData': 'Keine Vergleichsdaten. Bitte mehrere Perioden hochladen.',
    'comparison.noDataFiltered': 'Keine Daten gefunden mit diesen Filterkriterien.',
    'comparison.ofPositions': 'von',
    'comparison.positionsShown': 'Positionen angezeigt',
    
    // ===== GUEST MANAGEMENT VIEW =====
    'guestMgmt.title': 'Gästeverwaltung',
    'guestMgmt.description': 'Verwalten Sie Ihre Gäste und deren Aufenthalte',
    'guestMgmt.newGuest': 'Neuer Gast',
    'guestMgmt.addGuest': 'Neuen Gast anlegen',
    'guestMgmt.addGuestDesc': 'Erfassen Sie die Stammdaten des Gastes',
    'guestMgmt.searchGuests': 'Gäste durchsuchen...',
    'guestMgmt.totalGuests': 'Gäste gesamt',
    'guestMgmt.newThisMonth': 'Neu diesen Monat',
    'guestMgmt.vipGuests': 'VIP-Gäste',
    'guestMgmt.avgRevenue': 'Ø Umsatz',
    'guestMgmt.returningRate': 'Wiederkehrquote',
    'guestMgmt.salutation': 'Anrede',
    'guestMgmt.birthdate': 'Geburtsdatum',
    'guestMgmt.firstName': 'Vorname',
    'guestMgmt.lastName': 'Nachname',
    'guestMgmt.email': 'E-Mail',
    'guestMgmt.phone': 'Telefon',
    'guestMgmt.mobile': 'Mobil',
    'guestMgmt.street': 'Straße',
    'guestMgmt.zip': 'PLZ',
    'guestMgmt.city': 'Ort',
    'guestMgmt.country': 'Land',
    'guestMgmt.origin': 'Herkunftsland',
    'guestMgmt.language': 'Sprache',
    'guestMgmt.newsletter': 'Newsletter',
    'guestMgmt.marketing': 'Marketing-Einwilligung',
    'guestMgmt.allergies': 'Allergien',
    'guestMgmt.dietaryNotes': 'Ernährungshinweise',
    'guestMgmt.roomPreference': 'Zimmerpräferenz',
    'guestMgmt.specialRequests': 'Sonderwünsche',
    'guestMgmt.doctorApproval': 'Ärztliche Freigabe',
    'guestMgmt.medicalNotes': 'Medizinische Hinweise',
    'guestMgmt.vipStatus': 'VIP-Status',
    'guestMgmt.notes': 'Notizen',
    'guestMgmt.guestNumber': 'Gastnummer',
    'guestMgmt.name': 'Name',
    'guestMgmt.stays': 'Aufenthalte',
    'guestMgmt.totalRevenue': 'Gesamtumsatz',
    'guestMgmt.lastVisit': 'Letzter Besuch',
    'guestMgmt.guestCreated': 'Gast wurde erfolgreich angelegt',
    'guestMgmt.guestDeleted': 'Gast wurde gelöscht',
    'guestMgmt.stayCreated': 'Aufenthalt wurde erfolgreich angelegt',
    'guestMgmt.confirmDelete': 'Möchten Sie diesen Gast wirklich löschen?',
    'guestMgmt.loadError': 'Gäste konnten nicht geladen werden',
    'guestMgmt.addStay': 'Aufenthalt hinzufügen',
    'guestMgmt.guestDetails': 'Gastdetails',
    'guestMgmt.stayHistory': 'Aufenthaltshistorie',
    'guestMgmt.noStays': 'Keine Aufenthalte vorhanden',
    'guestMgmt.select': 'Auswählen',
    'guestMgmt.arrival': 'Anreise',
    'guestMgmt.departure': 'Abreise',
    'guestMgmt.nights': 'Nächte',
    'guestMgmt.guestType': 'Gasttyp',
    'guestMgmt.cureType': 'Kurtyp',
    'guestMgmt.bookingChannel': 'Buchungskanal',
    'guestMgmt.mealPlan': 'Verpflegung',
    'guestMgmt.roomNumber': 'Zimmernummer',
    'guestMgmt.roomCategory': 'Zimmerkategorie',
    'guestMgmt.pricePerNight': 'Preis/Nacht',
    'guestMgmt.totalPrice': 'Gesamtpreis',
    'guestMgmt.spaRevenue': 'Spa-Umsatz',
    'guestMgmt.fbRevenue': 'F&B-Umsatz',
    'guestMgmt.otherRevenue': 'Sonstige Umsätze',
    'guestMgmt.status': 'Status',
    'guestMgmt.guestList': 'Gästeliste',
    'guestMgmt.contact': 'Kontakt',
    'guestMgmt.noGuests': 'Keine Gäste gefunden',
    'guestMgmt.showing': 'Zeige',
    'guestMgmt.selectGuest': 'Gast auswählen',
    'guestMgmt.info': 'Info',
    'guestMgmt.preferences': 'Präferenzen',
    'guestMgmt.firstVisit': 'Erstbesuch',
    'guestMgmt.newStayFor': 'Neuer Aufenthalt für',
    
    // ===== KPI ALARMS VIEW =====
    'kpiAlarm.noThresholdsConfig': 'Noch keine Schwellenwerte konfiguriert. Klicken Sie auf "Schwellenwert hinzufügen".',
    'budgetPlan.title': 'Budgetplanung',
    'budgetPlan.description': 'Soll-Ist-Vergleich',
    'budgetPlan.noData': 'Keine Daten vorhanden',
    'budgetPlan.uploadHint': 'Laden Sie Ihre Saldenlisten hoch, um Budgets zu planen.',
    'budgetPlan.unsavedChanges': 'Ungespeicherte Änderungen',
    'budgetPlan.save': 'Speichern',
    'budgetPlan.saved': 'Budgets erfolgreich gespeichert',
    'budgetPlan.saveError': 'Fehler beim Speichern der Budgets',
    'budgetPlan.totalRevenue': 'Umsatz Gesamt',
    'budgetPlan.actual': 'IST',
    'budgetPlan.target': 'SOLL',
    'budgetPlan.db1Total': 'DB I Gesamt',
    'budgetPlan.db2Total': 'DB II Gesamt',
    'budgetPlan.deptBudgets': 'Abteilungs-Budgets',
    'budgetPlan.department': 'Abteilung',
    'budgetPlan.revenueBudget': 'Umsatz Budget',
    'budgetPlan.revenueActual': 'Umsatz IST',
    'budgetPlan.difference': 'Δ',
    'budgetPlan.cogsBudget': 'WE Budget',
    'budgetPlan.personnelBudget': 'Personal Budget',
    'budgetPlan.db1Calculated': 'DB I (berechnet)',
    'budgetPlan.db2Calculated': 'DB II (berechnet)',
    
    // ===== KPI ALARMS VIEW =====
    'kpiAlarm.title': 'KPI-Alarme & Schwellenwerte',
    'kpiAlarm.description': 'Überwachung und Benachrichtigung bei KPI-Abweichungen',
    'kpiAlarm.noData': 'Keine Daten vorhanden',
    'kpiAlarm.uploadHint': 'Laden Sie Ihre Saldenlisten hoch, um KPI-Alarme zu konfigurieren.',
    'kpiAlarm.activeAlarms': 'Aktive Alarme',
    'kpiAlarm.noAlarms': 'Alle KPIs im Normalbereich',
    'kpiAlarm.critical': 'kritisch',
    'kpiAlarm.warning': 'Warnung',
    'kpiAlarm.addThreshold': 'Schwellenwert hinzufügen',
    'kpiAlarm.newThreshold': 'Neuer Schwellenwert',
    'kpiAlarm.department': 'Abteilung',
    'kpiAlarm.kpiType': 'KPI-Typ',
    'kpiAlarm.minThreshold': 'Mindest-Schwellenwert',
    'kpiAlarm.maxThreshold': 'Maximum-Schwellenwert',
    'kpiAlarm.alarmActive': 'Alarm aktiv',
    'kpiAlarm.save': 'Speichern',
    'kpiAlarm.saved': 'Schwellenwert gespeichert',
    'kpiAlarm.deleted': 'Schwellenwert gelöscht',
    'kpiAlarm.thresholds': 'Schwellenwerte',
    'kpiAlarm.kpi': 'KPI',
    'kpiAlarm.min': 'Min',
    'kpiAlarm.max': 'Max',
    'kpiAlarm.currentValue': 'Aktueller Wert',
    'kpiAlarm.status': 'Status',
    'kpiAlarm.actions': 'Aktionen',
    'kpiAlarm.noDataAvailable': 'Keine Daten',
    'kpiAlarm.financeTab': 'Finanz-KPIs',
    'kpiAlarm.operationsTab': 'Operations-KPIs',
    'kpiAlarm.exportDoc': 'Dokumentation',
    
    // ===== EXPENSE MODAL =====
    'expense.totalExpenses': 'Gesamtaufwand',
    'expense.byAccountClass': 'Aufschlüsselung des Gesamtaufwands nach Kontoklassen (5-8)',
    'expense.previousMonth': 'Vormonat',
    'expense.previousYear': 'Vorjahr',
    'expense.byClass': 'Aufwand nach Kontoklasse',
    'expense.accountClass': 'Kontoklasse',
    'expense.current': 'Aktuell',
    'expense.trendPM': 'Trend VM',
    'expense.share': 'Anteil',
    'expense.diffPM': 'Differenz zum Vormonat',
    'expense.diffPY': 'Differenz zum Vorjahr',
    
    // ===== BEREICHE (AREAS/DEPARTMENTS) =====
    'area.logis': 'Logis',
    'area.fb': 'F&B',
    'area.rezeption': 'Rezeption',
    'area.spa': 'Spa',
    'area.aerztin': 'Ärztin',
    'area.shop': 'Shop',
    'area.verwaltung': 'Verwaltung',
    'area.technik': 'Technik',
    'area.energie': 'Energie',
    'area.marketing': 'Marketing',
    'area.personal': 'Personal',
    'area.finanzierung': 'Finanzierung',
    'area.sonstiges': 'Sonstiges',
    
    // ===== KPI-KATEGORIEN =====
    'kpiCat.erlos': 'Erlös',
    'kpiCat.wareneinsatz': 'Wareneinsatz',
    'kpiCat.personal': 'Personal',
    'kpiCat.betriebsaufwand': 'Betriebsaufwand',
    'kpiCat.energie': 'Energie',
    'kpiCat.marketing': 'Marketing',
    'kpiCat.abschreibung': 'Abschreibung',
    'kpiCat.zins': 'Zins',
    'kpiCat.sonstiges': 'Sonstiges',
    
    // ===== KOSTENART-TYPEN =====
    'costType.erlos': 'Erlös',
    'costType.einkauf': 'Einkauf',
    'costType.neutral': 'Neutral',
  },
  en: {
    // ===== NAVIGATION & SIDEBAR =====
    'nav.dashboard': 'Dashboard',
    'nav.guestManagement': 'Guest Management',
    'nav.departmentKpis': 'Department KPIs',
    'nav.overview': 'Overview',
    'nav.kpiTrends': 'KPI Trends',
    'nav.housekeeping': 'Housekeeping',
    'nav.kitchen': 'Kitchen',
    'nav.service': 'Service',
    'nav.frontoffice': 'Front Office',
    'nav.spa': 'Spa',
    'nav.technical': 'Technical',
    'nav.admin': 'Administration',
    'nav.personnelManagement': 'Personnel Management',
    'nav.employees': 'Employees',
    'nav.shiftPlanningAll': 'Shift Planning (All)',
    'nav.departmentShiftPlan': 'Department Shift Plan',
    'nav.timeAccounts': 'Time Accounts',
    'nav.personnelKpis': 'Personnel KPIs',
    'nav.planningAlarms': 'Planning & Alarms',
    'nav.budgetPlanning': 'Budget Planning',
    'nav.kpiAlarms': 'KPI Alarms',
    'nav.departmentHeads': 'Department Heads',
    'nav.userManagement': 'User Management',
    'nav.dataAnalysis': 'Data & Analysis',
    'nav.dataImport': 'Data Import',
    'nav.accountMaster': 'Account Master',
    'nav.periodComparison': 'Period Comparison',
    'nav.areaAnalysis': 'Area Analysis',
    'nav.dataQuality': 'Data Quality',
    'nav.financialAnalysis': 'Financial Analysis',
    'nav.hotelBalanceLists': 'Hotel Balance Lists',
    
    // ===== DASHBOARD =====
    'dashboard': 'Dashboard',
    'dashboard.description': 'Overview of your financial metrics',
    'dashboard.noData': 'No data available',
    'dashboard.uploadHint': 'Upload your balance lists to start the financial analysis.',
    'dashboard.expectedFormat': 'Expected format',
    'dashboard.financialOverview': 'Financial Overview',
    
    // ===== KPI CARDS =====
    'kpi.totalRevenue': 'Total Revenue',
    'kpi.fbRevenue': 'F&B Revenue',
    'kpi.totalExpenses': 'Total Expenses',
    'kpi.personnelCosts': 'Personnel Costs',
    'kpi.grossProfit': 'Gross Profit',
    'kpi.grossMargin': 'Gross Margin',
    'kpi.previousMonth': 'Previous Month',
    'kpi.previousYear': 'Previous Year',
    'kpi.pm': 'PM',
    'kpi.py': 'PY',
    
    // ===== TOOLTIPS =====
    'tooltip.revenue': 'Sum of all revenue accounts. Click for breakdown by area.',
    'tooltip.fb': 'Revenue from Food & Beverage (Restaurant, Kitchen, Bar, Banquet). Click for details.',
    'tooltip.expenses': 'Sum of all expense accounts classes 5-8. Click for breakdown.',
    'tooltip.personnel': 'Sum of all class 6 accounts (Wages, Salaries, Social Security). Click for breakdown.',
    'tooltip.grossProfit': 'Revenue − Expenses (Classes 5-8). Click for details.',
    'tooltip.grossMargin': 'Gross Profit ÷ Revenue × 100 – shows profitability in percent',
    
    // ===== CHARTS =====
    'chart.expensesByClass': 'Total Expenses by Account Class',
    'chart.revenueByArea': 'Revenue by Area',
    'chart.expensesByArea': 'Expenses by Area',
    'chart.materialExpenses': 'Material Expenses',
    'chart.personnelExpenses': 'Personnel Expenses',
    'chart.depreciation': 'Depreciation',
    'chart.otherExpenses': 'Other Expenses',
    
    // ===== ALARM WIDGET =====
    'alarm.title': 'KPI Alarms',
    'alarm.noThresholds': 'No thresholds configured',
    'alarm.allNormal': 'All KPIs within normal range',
    'alarm.critical': 'critical',
    'alarm.warning': 'warning',
    'alarm.moreAlarms': 'more alarms',
    
    // ===== BUDGET WIDGET =====
    'budget.deviations': 'Budget Deviations (Target vs Actual)',
    'budget.noData': 'No budget data available for this month',
    'budget.revenue': 'Revenue',
    'budget.personnel': 'Personnel',
    
    // ===== UPLOAD VIEW =====
    'upload.title': 'Balance List Import',
    'upload.description': 'Import CSV files from your accounting system',
    'upload.dropzone': 'Drop balance lists here or click to browse',
    'upload.accepted': 'Accepted: CSV, Excel',
    'upload.importedFiles': 'Imported Files',
    'upload.noFiles': 'No files imported yet',
    'upload.accounts': 'Accounts',
    'upload.deleteAll': 'Delete all data',
    'upload.confirmDelete': 'All imported data will be permanently deleted.',
    'upload.success': 'Import successful',
    'upload.accountsImported': 'accounts imported for',
    'upload.error': 'Import error',
    
    // ===== ACCOUNTS VIEW =====
    'accounts.title': 'Account Master',
    'accounts.description': 'Overview of all accounts with assignments',
    'accounts.accountNumber': 'Account Number',
    'accounts.description2': 'Description',
    'accounts.class': 'Class',
    'accounts.area': 'Area',
    'accounts.type': 'Cost Type',
    'accounts.kpiCategory': 'KPI Category',
    'accounts.currentBalance': 'Current Balance',
    'accounts.search': 'Search accounts...',
    'accounts.all': 'All',
    'accounts.totalAccounts': 'Total accounts',
    'accounts.withBalance': 'with balance',
    
    
    // ===== DATA QUALITY VIEW =====
    'dataQuality.title': 'Data Quality',
    'dataQuality.description': 'Analysis of data quality and completeness',
    'dataQuality.complete': 'Complete',
    'dataQuality.incomplete': 'Incomplete',
    'dataQuality.missing': 'Missing',
    
    // ===== EMPLOYEES VIEW =====
    'employees.title': 'Employee Master Data',
    'employees.description': 'Overview of all employees',
    'employees.personnelNumber': 'Personnel No.',
    'employees.firstName': 'First Name',
    'employees.lastName': 'Last Name',
    'employees.department': 'Department',
    'employees.position': 'Position',
    'employees.employmentType': 'Employment Type',
    'employees.weeklyHours': 'Weekly Hours',
    'employees.hourlyRate': 'Hourly Rate',
    'employees.entryDate': 'Entry Date',
    'employees.status': 'Status',
    'employees.active': 'Active',
    'employees.inactive': 'Inactive',
    'employees.addNew': 'New Employee',
    'employees.search': 'Search employees...',
    'employees.total': 'Total employees',
    'employees.activeCount': 'active',
    
    // ===== SHIFT PLANNING =====
    'shifts.title': 'Shift Planning',
    'shifts.description': 'Weekly shift planning',
    'shifts.week': 'Week',
    'shifts.employee': 'Employee',
    'shifts.monday': 'Monday',
    'shifts.tuesday': 'Tuesday',
    'shifts.wednesday': 'Wednesday',
    'shifts.thursday': 'Thursday',
    'shifts.friday': 'Friday',
    'shifts.saturday': 'Saturday',
    'shifts.sunday': 'Sunday',
    'shifts.work': 'Work',
    'shifts.vacation': 'Vacation',
    'shifts.sick': 'Sick',
    'shifts.training': 'Training',
    'shifts.free': 'Off',
    'shifts.overtime': 'Overtime Reduction',
    'shifts.parentalLeave': 'Parental Leave',
    'shifts.other': 'Other',
    'shifts.plannedHours': 'Planned Hours',
    'shifts.actualHours': 'Actual Hours',
    'shifts.overtimeHours': 'Overtime',
    'shifts.printView': 'Print View',
    'shifts.pdfExport': 'PDF Export',
    'shifts.sendToHead': 'Send to Manager',
    'shifts.selectDepartment': 'Select Department',
    'shifts.legend': 'Legend',
    'shifts.planningRate': 'Planning Rate',
    'shifts.sickDays': 'Sick Days',
    'shifts.vacationDays': 'Vacation Days',
    'shifts.workDays': 'Work Days',
    'shifts.summary': 'Summary',
    
    // ===== TIME ACCOUNTS =====
    'timeAccounts.title': 'Time Accounts',
    'timeAccounts.description': 'Overtime and vacation accounts',
    'timeAccounts.overtimeBalance': 'Overtime Balance',
    'timeAccounts.vacationEntitlement': 'Vacation Entitlement',
    'timeAccounts.vacationTaken': 'Vacation Taken',
    'timeAccounts.vacationRemaining': 'Remaining Vacation',
    'timeAccounts.sickDays': 'Sick Days',
    
    // ===== BUDGET PLANNING =====
    'budgetPlanning.title': 'Budget Planning',
    'budgetPlanning.description': 'Annual budgets and variance analysis',
    'budgetPlanning.budget': 'Budget',
    'budgetPlanning.actual': 'Actual',
    'budgetPlanning.deviation': 'Deviation',
    'budgetPlanning.year': 'Year',
    'budgetPlanning.month': 'Month',
    
    // ===== KPI ALARMS =====
    'kpiAlarms.title': 'KPI Alarms & Thresholds',
    'kpiAlarms.description': 'Configuration of limits and notifications',
    'kpiAlarms.threshold': 'Threshold',
    'kpiAlarms.min': 'Minimum',
    'kpiAlarms.max': 'Maximum',
    'kpiAlarms.alarmActive': 'Alarm Active',
    'kpiAlarms.addThreshold': 'Add Threshold',
    
    // ===== DEPARTMENT HEADS =====
    'deptHeads.title': 'Department Heads',
    'deptHeads.description': 'Responsible managers by area',
    'deptHeads.name': 'Name',
    'deptHeads.email': 'Email',
    'deptHeads.department': 'Department',
    'deptHeads.active': 'Active',
    
    // ===== USER MANAGEMENT =====
    'userMgmt.title': 'User Management',
    'userMgmt.description': 'Manage users and permissions',
    'userMgmt.user': 'User',
    'userMgmt.role': 'Role',
    'userMgmt.admin': 'Administrator',
    'userMgmt.deptHead': 'Department Head',
    'userMgmt.employee': 'Employee',
    'userMgmt.inviteUser': 'Invite User',
    
    // ===== GUEST MANAGEMENT VIEW =====
    'guestMgmt.title': 'Guest Management',
    'guestMgmt.description': 'Manage your guests and their stays',
    'guestMgmt.newGuest': 'New Guest',
    'guestMgmt.addGuest': 'Add New Guest',
    'guestMgmt.addGuestDesc': 'Enter the guest master data',
    'guestMgmt.searchGuests': 'Search guests...',
    'guestMgmt.totalGuests': 'Total Guests',
    'guestMgmt.newThisMonth': 'New This Month',
    'guestMgmt.vipGuests': 'VIP Guests',
    'guestMgmt.avgRevenue': 'Avg Revenue',
    'guestMgmt.returningRate': 'Returning Rate',
    'guestMgmt.salutation': 'Salutation',
    'guestMgmt.birthdate': 'Date of Birth',
    'guestMgmt.firstName': 'First Name',
    'guestMgmt.lastName': 'Last Name',
    'guestMgmt.email': 'Email',
    'guestMgmt.phone': 'Phone',
    'guestMgmt.mobile': 'Mobile',
    'guestMgmt.street': 'Street',
    'guestMgmt.zip': 'ZIP Code',
    'guestMgmt.city': 'City',
    'guestMgmt.country': 'Country',
    'guestMgmt.origin': 'Country of Origin',
    'guestMgmt.language': 'Language',
    'guestMgmt.newsletter': 'Newsletter',
    'guestMgmt.marketing': 'Marketing Consent',
    'guestMgmt.allergies': 'Allergies',
    'guestMgmt.dietaryNotes': 'Dietary Notes',
    'guestMgmt.roomPreference': 'Room Preference',
    'guestMgmt.specialRequests': 'Special Requests',
    'guestMgmt.doctorApproval': 'Doctor Approval',
    'guestMgmt.medicalNotes': 'Medical Notes',
    'guestMgmt.vipStatus': 'VIP Status',
    'guestMgmt.notes': 'Notes',
    'guestMgmt.guestNumber': 'Guest Number',
    'guestMgmt.name': 'Name',
    'guestMgmt.stays': 'Stays',
    'guestMgmt.totalRevenue': 'Total Revenue',
    'guestMgmt.lastVisit': 'Last Visit',
    'guestMgmt.guestCreated': 'Guest created successfully',
    'guestMgmt.guestDeleted': 'Guest deleted',
    'guestMgmt.stayCreated': 'Stay created successfully',
    'guestMgmt.confirmDelete': 'Are you sure you want to delete this guest?',
    'guestMgmt.loadError': 'Could not load guests',
    'guestMgmt.addStay': 'Add Stay',
    'guestMgmt.guestDetails': 'Guest Details',
    'guestMgmt.stayHistory': 'Stay History',
    'guestMgmt.noStays': 'No stays available',
    'guestMgmt.select': 'Select',
    'guestMgmt.arrival': 'Arrival',
    'guestMgmt.departure': 'Departure',
    'guestMgmt.nights': 'Nights',
    'guestMgmt.guestType': 'Guest Type',
    'guestMgmt.cureType': 'Cure Type',
    'guestMgmt.bookingChannel': 'Booking Channel',
    'guestMgmt.mealPlan': 'Meal Plan',
    'guestMgmt.roomNumber': 'Room Number',
    'guestMgmt.roomCategory': 'Room Category',
    'guestMgmt.pricePerNight': 'Price/Night',
    'guestMgmt.totalPrice': 'Total Price',
    'guestMgmt.spaRevenue': 'Spa Revenue',
    'guestMgmt.fbRevenue': 'F&B Revenue',
    'guestMgmt.otherRevenue': 'Other Revenue',
    'guestMgmt.status': 'Status',
    'guestMgmt.guestList': 'Guest List',
    'guestMgmt.contact': 'Contact',
    'guestMgmt.noGuests': 'No guests found',
    'guestMgmt.showing': 'Showing',
    'guestMgmt.selectGuest': 'Select a guest',
    'guestMgmt.info': 'Info',
    'guestMgmt.preferences': 'Preferences',
    'guestMgmt.firstVisit': 'First Visit',
    'guestMgmt.newStayFor': 'New stay for',
    
    // ===== KPI ALARMS VIEW =====
    'kpiAlarm.noThresholdsConfig': 'No thresholds configured yet. Click "Add Threshold".',
    'budgetPlan.title': 'Budget Planning',
    'budgetPlan.description': 'Target vs Actual Comparison',
    'budgetPlan.noData': 'No data available',
    'budgetPlan.uploadHint': 'Upload your balance lists to plan budgets.',
    'budgetPlan.unsavedChanges': 'Unsaved Changes',
    'budgetPlan.save': 'Save',
    'budgetPlan.saved': 'Budgets saved successfully',
    'budgetPlan.saveError': 'Error saving budgets',
    'budgetPlan.totalRevenue': 'Total Revenue',
    'budgetPlan.actual': 'Actual',
    'budgetPlan.target': 'Target',
    'budgetPlan.db1Total': 'CM I Total',
    'budgetPlan.db2Total': 'CM II Total',
    'budgetPlan.deptBudgets': 'Department Budgets',
    'budgetPlan.department': 'Department',
    'budgetPlan.revenueBudget': 'Revenue Budget',
    'budgetPlan.revenueActual': 'Revenue Actual',
    'budgetPlan.difference': 'Δ',
    'budgetPlan.cogsBudget': 'COGS Budget',
    'budgetPlan.personnelBudget': 'Personnel Budget',
    'budgetPlan.db1Calculated': 'CM I (calculated)',
    'budgetPlan.db2Calculated': 'CM II (calculated)',
    
    // ===== KPI ALARMS VIEW =====
    'kpiAlarm.title': 'KPI Alarms & Thresholds',
    'kpiAlarm.description': 'Monitor and notify on KPI deviations',
    'kpiAlarm.noData': 'No data available',
    'kpiAlarm.uploadHint': 'Upload your balance lists to configure KPI alarms.',
    'kpiAlarm.activeAlarms': 'Active Alarms',
    'kpiAlarm.noAlarms': 'All KPIs within normal range',
    'kpiAlarm.critical': 'critical',
    'kpiAlarm.warning': 'warning',
    'kpiAlarm.addThreshold': 'Add Threshold',
    'kpiAlarm.newThreshold': 'New Threshold',
    'kpiAlarm.department': 'Department',
    'kpiAlarm.kpiType': 'KPI Type',
    'kpiAlarm.minThreshold': 'Minimum Threshold',
    'kpiAlarm.maxThreshold': 'Maximum Threshold',
    'kpiAlarm.alarmActive': 'Alarm Active',
    'kpiAlarm.save': 'Save',
    'kpiAlarm.saved': 'Threshold saved',
    'kpiAlarm.deleted': 'Threshold deleted',
    'kpiAlarm.thresholds': 'Thresholds',
    'kpiAlarm.kpi': 'KPI',
    'kpiAlarm.min': 'Min',
    'kpiAlarm.max': 'Max',
    'kpiAlarm.currentValue': 'Current Value',
    'kpiAlarm.status': 'Status',
    'kpiAlarm.actions': 'Actions',
    'kpiAlarm.noDataAvailable': 'No data',
    'kpiAlarm.financeTab': 'Finance KPIs',
    'kpiAlarm.operationsTab': 'Operations KPIs',
    'kpiAlarm.exportDoc': 'Documentation',
    
    // ===== GUEST MANAGEMENT =====
    'guests.title': 'Guest Management',
    'guests.description': 'Guest data and stays',
    'guests.guestNumber': 'Guest Number',
    'guests.name': 'Name',
    'guests.email': 'Email',
    'guests.phone': 'Phone',
    'guests.stays': 'Stays',
    'guests.totalRevenue': 'Total Revenue',
    'guests.vip': 'VIP',
    'guests.addGuest': 'New Guest',
    'guests.search': 'Search guests...',
    
    // ===== COMMON =====
    'common.loading': 'Loading...',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.add': 'Add',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.export': 'Export',
    'common.import': 'Import',
    'common.print': 'Print',
    'common.close': 'Close',
    'common.confirm': 'Confirm',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.actions': 'Actions',
    'common.status': 'Status',
    'common.date': 'Date',
    'common.time': 'Time',
    'common.total': 'Total',
    'common.details': 'Details',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.handbook': 'Handbook',
    'common.language': 'Language',
    'common.german': 'Deutsch',
    'common.english': 'English',
    'common.hindi': 'हिन्दी',
    'common.noData': 'No data available',
    'common.error': 'Error',
    'common.success': 'Success',
    
    // ===== MONTHS =====
    'month.january': 'January',
    'month.february': 'February',
    'month.march': 'March',
    'month.april': 'April',
    'month.may': 'May',
    'month.june': 'June',
    'month.july': 'July',
    'month.august': 'August',
    'month.september': 'September',
    'month.october': 'October',
    'month.november': 'November',
    'month.december': 'December',
    
    // ===== DAYS =====
    'day.mon': 'Mon',
    'day.tue': 'Tue',
    'day.wed': 'Wed',
    'day.thu': 'Thu',
    'day.fri': 'Fri',
    'day.sat': 'Sat',
    'day.sun': 'Sun',
    
    // ===== DEPARTMENT KPIs =====
    'deptKpi.title': 'Department KPIs',
    'deptKpi.description': 'Contribution margin analysis by department',
    'deptKpi.noData': 'No data available',
    'deptKpi.uploadHint': 'Upload your balance lists to calculate department KPIs.',
    'deptKpi.yearComparison': 'Year Comparison',
    'deptKpi.vs': 'vs.',
    'deptKpi.operativeDepts': 'Operative Departments',
    'deptKpi.clickForDetails': '(click for account details)',
    'deptKpi.serviceDepts': 'Service Areas (Cost Overview)',
    'deptKpi.accountDetails': 'Account Details',
    'deptKpi.accountsWithBalance': 'Accounts with balance',
    'deptKpi.noAccountBalances': 'No account balances for this period',
    'deptKpi.totalRevenue': 'Total Revenue',
    'deptKpi.cogs': 'Cost of Goods Sold',
    'deptKpi.db1Total': 'Contribution Margin I Total',
    'deptKpi.personnel': 'Personnel',
    'deptKpi.db2Total': 'Contribution Margin II Total',
    'deptKpi.energy': 'Energy',
    'deptKpi.revenue': 'Revenue',
    'deptKpi.db1': 'CM I',
    'deptKpi.db2': 'CM II',
    'deptKpi.operatingExpenses': 'Operating Expenses',
    'deptKpi.marketing': 'Marketing',
    'deptKpi.total': 'Total',
    'deptKpi.vsLastYear': 'vs. Last Year',
    'deptKpi.py': 'PY',
    'deptKpi.pyShort': 'PY',
    'deptKpi.exportSuccess': 'KPI export created successfully',
    'deptKpi.revenueCurrent': 'Revenue Current',
    'deptKpi.revenuePY': 'Revenue PY',
    'deptKpi.db2Current': 'CM II Current',
    'deptKpi.db2PY': 'CM II PY',
    
    // ===== AREA ANALYSIS VIEW =====
    'areas.title': 'Area Analysis',
    'areas.description': 'Aggregated values by business area',
    'areas.noData': 'No data available. Please upload balance lists.',
    'areas.revenueByArea': 'Revenue by Area',
    'areas.expensesByArea': 'Expenses by Area',
    'areas.noRevenueData': 'No revenue data',
    'areas.noExpenseData': 'No expense data',
    
    // ===== COMPARISON VIEW =====
    'comparison.title': 'Period Comparison',
    'comparison.description': 'Comparison',
    'comparison.vsPMAndPY': 'vs. Previous Month & Previous Year',
    'comparison.searchAccount': 'Search account...',
    'comparison.allAreas': 'All Areas',
    'comparison.allTypes': 'All Types',
    'comparison.revenue': 'Revenue',
    'comparison.expense': 'Expense',
    'comparison.account': 'Account',
    'comparison.designation': 'Description',
    'comparison.current': 'Current',
    'comparison.prevMonth': 'Previous Month',
    'comparison.pmDiff': 'PM Δ',
    'comparison.prevYear': 'Previous Year',
    'comparison.pyDiff': 'PY Δ',
    'comparison.noData': 'No comparison data. Please upload multiple periods.',
    'comparison.noDataFiltered': 'No data found with these filter criteria.',
    'comparison.ofPositions': 'of',
    'comparison.positionsShown': 'positions shown',
    
    // ===== EXPENSE MODAL =====
    'expense.totalExpenses': 'Total Expenses',
    'expense.byAccountClass': 'Breakdown of total expenses by account classes (5-8)',
    'expense.previousMonth': 'Previous Month',
    'expense.previousYear': 'Previous Year',
    'expense.byClass': 'Expenses by Account Class',
    'expense.accountClass': 'Account Class',
    'expense.current': 'Current',
    'expense.trendPM': 'Trend PM',
    'expense.share': 'Share',
    'expense.diffPM': 'Difference to Previous Month',
    'expense.diffPY': 'Difference to Previous Year',
    
    // ===== BEREICHE (AREAS/DEPARTMENTS) =====
    'area.logis': 'Accommodation',
    'area.fb': 'F&B',
    'area.rezeption': 'Front Office',
    'area.spa': 'Spa',
    'area.aerztin': 'Medical',
    'area.shop': 'Shop',
    'area.verwaltung': 'Administration',
    'area.technik': 'Technical',
    'area.energie': 'Energy',
    'area.marketing': 'Marketing',
    'area.personal': 'Personnel',
    'area.finanzierung': 'Financing',
    'area.sonstiges': 'Other',
    
    // ===== KPI-KATEGORIEN =====
    'kpiCat.erlos': 'Revenue',
    'kpiCat.wareneinsatz': 'Cost of Goods',
    'kpiCat.personal': 'Personnel',
    'kpiCat.betriebsaufwand': 'Operating Expenses',
    'kpiCat.energie': 'Energy',
    'kpiCat.marketing': 'Marketing',
    'kpiCat.abschreibung': 'Depreciation',
    'kpiCat.zins': 'Interest',
    'kpiCat.sonstiges': 'Other',
    
    // ===== KOSTENART-TYPEN =====
    'costType.erlos': 'Revenue',
    'costType.einkauf': 'Expense',
    'costType.neutral': 'Neutral',
  },
  hi: {
    // ===== NAVIGATION & SIDEBAR =====
    'nav.dashboard': 'डैशबोर्ड',
    'nav.guestManagement': 'अतिथि प्रबंधन',
    'nav.departmentKpis': 'विभाग KPIs',
    'nav.overview': 'अवलोकन',
    'nav.kpiTrends': 'KPI रुझान',
    'nav.housekeeping': 'हाउसकीपिंग',
    'nav.kitchen': 'रसोई',
    'nav.service': 'सेवा',
    'nav.frontoffice': 'फ्रंट ऑफिस',
    'nav.spa': 'स्पा',
    'nav.technical': 'तकनीकी',
    'nav.admin': 'प्रशासन',
    'nav.personnelManagement': 'कर्मचारी प्रबंधन',
    'nav.employees': 'कर्मचारी',
    'nav.shiftPlanningAll': 'शिफ्ट योजना (सभी)',
    'nav.departmentShiftPlan': 'विभाग शिफ्ट योजना',
    'nav.timeAccounts': 'समय खाते',
    'nav.personnelKpis': 'कर्मचारी KPIs',
    'nav.planningAlarms': 'योजना और अलार्म',
    'nav.budgetPlanning': 'बजट योजना',
    'nav.kpiAlarms': 'KPI अलार्म',
    'nav.departmentHeads': 'विभाग प्रमुख',
    'nav.userManagement': 'उपयोगकर्ता प्रबंधन',
    'nav.dataAnalysis': 'डेटा और विश्लेषण',
    'nav.dataImport': 'डेटा आयात',
    'nav.accountMaster': 'खाता मास्टर',
    'nav.periodComparison': 'अवधि तुलना',
    'nav.areaAnalysis': 'क्षेत्र विश्लेषण',
    'nav.dataQuality': 'डेटा गुणवत्ता',
    'nav.financialAnalysis': 'वित्तीय विश्लेषण',
    'nav.hotelBalanceLists': 'होटल शेष सूची',
    
    // ===== DASHBOARD =====
    'dashboard': 'डैशबोर्ड',
    'dashboard.description': 'आपके वित्तीय आंकड़ों का अवलोकन',
    'dashboard.noData': 'कोई डेटा उपलब्ध नहीं',
    'dashboard.uploadHint': 'वित्तीय विश्लेषण शुरू करने के लिए अपनी शेष सूची अपलोड करें।',
    'dashboard.expectedFormat': 'अपेक्षित प्रारूप',
    'dashboard.financialOverview': 'वित्तीय अवलोकन',
    
    // ===== KPI CARDS =====
    'kpi.totalRevenue': 'कुल राजस्व',
    'kpi.fbRevenue': 'F&B राजस्व',
    'kpi.totalExpenses': 'कुल व्यय',
    'kpi.personnelCosts': 'कर्मचारी लागत',
    'kpi.grossProfit': 'सकल लाभ',
    'kpi.grossMargin': 'सकल मार्जिन',
    'kpi.previousMonth': 'पिछला महीना',
    'kpi.previousYear': 'पिछला वर्ष',
    'kpi.pm': 'पिम',
    'kpi.py': 'पिव',
    
    // ===== TOOLTIPS =====
    'tooltip.revenue': 'सभी राजस्व खातों का योग। क्षेत्र के अनुसार विवरण के लिए क्लिक करें।',
    'tooltip.fb': 'खाद्य एवं पेय पदार्थ से राजस्व (रेस्तरां, रसोई, बार, भोज)। विवरण के लिए क्लिक करें।',
    'tooltip.expenses': 'सभी व्यय खातों का योग वर्ग 5-8। विवरण के लिए क्लिक करें।',
    'tooltip.personnel': 'सभी वर्ग 6 खातों का योग (मजदूरी, वेतन, सामाजिक सुरक्षा)। विवरण के लिए क्लिक करें।',
    'tooltip.grossProfit': 'राजस्व − व्यय (वर्ग 5-8)। विवरण के लिए क्लिक करें।',
    'tooltip.grossMargin': 'सकल लाभ ÷ राजस्व × 100 – प्रतिशत में लाभप्रदता दर्शाता है',
    
    // ===== CHARTS =====
    'chart.expensesByClass': 'खाता वर्ग के अनुसार कुल व्यय',
    'chart.revenueByArea': 'क्षेत्र के अनुसार राजस्व',
    'chart.expensesByArea': 'क्षेत्र के अनुसार व्यय',
    'chart.materialExpenses': 'सामग्री व्यय',
    'chart.personnelExpenses': 'कर्मचारी व्यय',
    'chart.depreciation': 'मूल्यह्रास',
    'chart.otherExpenses': 'अन्य व्यय',
    
    // ===== ALARM WIDGET =====
    'alarm.title': 'KPI अलार्म',
    'alarm.noThresholds': 'कोई सीमा कॉन्फ़िगर नहीं',
    'alarm.allNormal': 'सभी KPIs सामान्य सीमा में',
    'alarm.critical': 'गंभीर',
    'alarm.warning': 'चेतावनी',
    'alarm.moreAlarms': 'और अलार्म',
    
    // ===== BUDGET WIDGET =====
    'budget.deviations': 'बजट विचलन (लक्ष्य बनाम वास्तविक)',
    'budget.noData': 'इस महीने के लिए कोई बजट डेटा उपलब्ध नहीं',
    'budget.revenue': 'राजस्व',
    'budget.personnel': 'कर्मचारी',
    
    // ===== UPLOAD VIEW =====
    'upload.title': 'शेष सूची आयात',
    'upload.description': 'अपने लेखा प्रणाली से CSV फ़ाइलें आयात करें',
    'upload.dropzone': 'शेष सूची यहाँ छोड़ें या ब्राउज़ करने के लिए क्लिक करें',
    'upload.accepted': 'स्वीकृत: CSV, Excel',
    'upload.importedFiles': 'आयातित फ़ाइलें',
    'upload.noFiles': 'अभी तक कोई फ़ाइल आयात नहीं',
    'upload.accounts': 'खाते',
    'upload.deleteAll': 'सभी डेटा हटाएं',
    'upload.confirmDelete': 'सभी आयातित डेटा स्थायी रूप से हटा दिया जाएगा।',
    'upload.success': 'आयात सफल',
    'upload.accountsImported': 'खाते आयात किए गए',
    'upload.error': 'आयात त्रुटि',
    
    // ===== ACCOUNTS VIEW =====
    'accounts.title': 'खाता मास्टर',
    'accounts.description': 'असाइनमेंट के साथ सभी खातों का अवलोकन',
    'accounts.accountNumber': 'खाता संख्या',
    'accounts.description2': 'विवरण',
    'accounts.class': 'वर्ग',
    'accounts.area': 'क्षेत्र',
    'accounts.type': 'लागत प्रकार',
    'accounts.kpiCategory': 'KPI श्रेणी',
    'accounts.currentBalance': 'वर्तमान शेष',
    'accounts.search': 'खाते खोजें...',
    'accounts.all': 'सभी',
    'accounts.totalAccounts': 'कुल खाते',
    'accounts.withBalance': 'शेष के साथ',
    
    
    // ===== DATA QUALITY VIEW =====
    'dataQuality.title': 'डेटा गुणवत्ता',
    'dataQuality.description': 'डेटा गुणवत्ता और पूर्णता का विश्लेषण',
    'dataQuality.complete': 'पूर्ण',
    'dataQuality.incomplete': 'अपूर्ण',
    'dataQuality.missing': 'गुम',
    
    // ===== EMPLOYEES VIEW =====
    'employees.title': 'कर्मचारी मास्टर डेटा',
    'employees.description': 'सभी कर्मचारियों का अवलोकन',
    'employees.personnelNumber': 'कर्मचारी सं.',
    'employees.firstName': 'पहला नाम',
    'employees.lastName': 'अंतिम नाम',
    'employees.department': 'विभाग',
    'employees.position': 'पद',
    'employees.employmentType': 'रोजगार प्रकार',
    'employees.weeklyHours': 'साप्ताहिक घंटे',
    'employees.hourlyRate': 'प्रति घंटा दर',
    'employees.entryDate': 'प्रवेश तिथि',
    'employees.status': 'स्थिति',
    'employees.active': 'सक्रिय',
    'employees.inactive': 'निष्क्रिय',
    'employees.addNew': 'नया कर्मचारी',
    'employees.search': 'कर्मचारी खोजें...',
    'employees.total': 'कुल कर्मचारी',
    'employees.activeCount': 'सक्रिय',
    
    // ===== SHIFT PLANNING =====
    'shifts.title': 'शिफ्ट योजना',
    'shifts.description': 'साप्ताहिक शिफ्ट योजना',
    'shifts.week': 'सप्ताह',
    'shifts.employee': 'कर्मचारी',
    'shifts.monday': 'सोमवार',
    'shifts.tuesday': 'मंगलवार',
    'shifts.wednesday': 'बुधवार',
    'shifts.thursday': 'गुरुवार',
    'shifts.friday': 'शुक्रवार',
    'shifts.saturday': 'शनिवार',
    'shifts.sunday': 'रविवार',
    'shifts.work': 'कार्य',
    'shifts.vacation': 'छुट्टी',
    'shifts.sick': 'बीमार',
    'shifts.training': 'प्रशिक्षण',
    'shifts.free': 'मुक्त',
    'shifts.overtime': 'ओवरटाइम कटौती',
    'shifts.parentalLeave': 'माता-पिता की छुट्टी',
    'shifts.other': 'अन्य',
    'shifts.plannedHours': 'नियोजित घंटे',
    'shifts.actualHours': 'वास्तविक घंटे',
    'shifts.overtimeHours': 'ओवरटाइम',
    'shifts.printView': 'प्रिंट दृश्य',
    'shifts.pdfExport': 'PDF निर्यात',
    'shifts.sendToHead': 'प्रबंधक को भेजें',
    'shifts.selectDepartment': 'विभाग चुनें',
    'shifts.legend': 'लीजेंड',
    'shifts.planningRate': 'योजना दर',
    'shifts.sickDays': 'बीमारी के दिन',
    'shifts.vacationDays': 'छुट्टी के दिन',
    'shifts.workDays': 'कार्य दिवस',
    'shifts.summary': 'सारांश',
    
    // ===== TIME ACCOUNTS =====
    'timeAccounts.title': 'समय खाते',
    'timeAccounts.description': 'ओवरटाइम और छुट्टी खाते',
    'timeAccounts.overtimeBalance': 'ओवरटाइम शेष',
    'timeAccounts.vacationEntitlement': 'छुट्टी का हक',
    'timeAccounts.vacationTaken': 'ली गई छुट्टी',
    'timeAccounts.vacationRemaining': 'शेष छुट्टी',
    'timeAccounts.sickDays': 'बीमारी के दिन',
    
    // ===== BUDGET PLANNING =====
    'budgetPlanning.title': 'बजट योजना',
    'budgetPlanning.description': 'वार्षिक बजट और विचलन विश्लेषण',
    'budgetPlanning.budget': 'बजट',
    'budgetPlanning.actual': 'वास्तविक',
    'budgetPlanning.deviation': 'विचलन',
    'budgetPlanning.year': 'वर्ष',
    'budgetPlanning.month': 'महीना',
    
    // ===== KPI ALARMS =====
    'kpiAlarms.title': 'KPI अलार्म और सीमाएं',
    'kpiAlarms.description': 'सीमाओं और सूचनाओं का कॉन्फ़िगरेशन',
    'kpiAlarms.threshold': 'सीमा',
    'kpiAlarms.min': 'न्यूनतम',
    'kpiAlarms.max': 'अधिकतम',
    'kpiAlarms.alarmActive': 'अलार्म सक्रिय',
    'kpiAlarms.addThreshold': 'सीमा जोड़ें',
    
    // ===== DEPARTMENT HEADS =====
    'deptHeads.title': 'विभाग प्रमुख',
    'deptHeads.description': 'क्षेत्र के अनुसार जिम्मेदार प्रबंधक',
    'deptHeads.name': 'नाम',
    'deptHeads.email': 'ईमेल',
    'deptHeads.department': 'विभाग',
    'deptHeads.active': 'सक्रिय',
    
    // ===== USER MANAGEMENT =====
    'userMgmt.title': 'उपयोगकर्ता प्रबंधन',
    'userMgmt.description': 'उपयोगकर्ताओं और अनुमतियों का प्रबंधन',
    'userMgmt.user': 'उपयोगकर्ता',
    'userMgmt.role': 'भूमिका',
    'userMgmt.admin': 'व्यवस्थापक',
    'userMgmt.deptHead': 'विभाग प्रमुख',
    'userMgmt.employee': 'कर्मचारी',
    'userMgmt.inviteUser': 'उपयोगकर्ता आमंत्रित करें',
    
    // ===== GUEST MANAGEMENT VIEW =====
    'guestMgmt.title': 'अतिथि प्रबंधन',
    'guestMgmt.description': 'अपने अतिथियों और उनके ठहराव का प्रबंधन करें',
    'guestMgmt.newGuest': 'नया अतिथि',
    'guestMgmt.addGuest': 'नया अतिथि जोड़ें',
    'guestMgmt.addGuestDesc': 'अतिथि का मास्टर डेटा दर्ज करें',
    'guestMgmt.searchGuests': 'अतिथि खोजें...',
    'guestMgmt.totalGuests': 'कुल अतिथि',
    'guestMgmt.newThisMonth': 'इस महीने नए',
    'guestMgmt.vipGuests': 'VIP अतिथि',
    'guestMgmt.avgRevenue': 'औसत राजस्व',
    'guestMgmt.returningRate': 'वापसी दर',
    'guestMgmt.salutation': 'संबोधन',
    'guestMgmt.birthdate': 'जन्म तिथि',
    'guestMgmt.firstName': 'पहला नाम',
    'guestMgmt.lastName': 'अंतिम नाम',
    'guestMgmt.email': 'ईमेल',
    'guestMgmt.phone': 'फ़ोन',
    'guestMgmt.mobile': 'मोबाइल',
    'guestMgmt.street': 'गली',
    'guestMgmt.zip': 'पिन कोड',
    'guestMgmt.city': 'शहर',
    'guestMgmt.country': 'देश',
    'guestMgmt.origin': 'मूल देश',
    'guestMgmt.language': 'भाषा',
    'guestMgmt.newsletter': 'न्यूज़लेटर',
    'guestMgmt.marketing': 'विपणन सहमति',
    'guestMgmt.allergies': 'एलर्जी',
    'guestMgmt.dietaryNotes': 'आहार संबंधी नोट',
    'guestMgmt.roomPreference': 'कमरे की प्राथमिकता',
    'guestMgmt.specialRequests': 'विशेष अनुरोध',
    'guestMgmt.doctorApproval': 'डॉक्टर की मंजूरी',
    'guestMgmt.medicalNotes': 'चिकित्सा नोट',
    'guestMgmt.vipStatus': 'VIP स्थिति',
    'guestMgmt.notes': 'नोट्स',
    'guestMgmt.guestNumber': 'अतिथि संख्या',
    'guestMgmt.name': 'नाम',
    'guestMgmt.stays': 'ठहराव',
    'guestMgmt.totalRevenue': 'कुल राजस्व',
    'guestMgmt.lastVisit': 'अंतिम यात्रा',
    'guestMgmt.guestCreated': 'अतिथि सफलतापूर्वक बनाया गया',
    'guestMgmt.guestDeleted': 'अतिथि हटाया गया',
    'guestMgmt.stayCreated': 'ठहराव सफलतापूर्वक बनाया गया',
    'guestMgmt.confirmDelete': 'क्या आप वाकई इस अतिथि को हटाना चाहते हैं?',
    'guestMgmt.loadError': 'अतिथियों को लोड नहीं किया जा सका',
    'guestMgmt.addStay': 'ठहराव जोड़ें',
    'guestMgmt.guestDetails': 'अतिथि विवरण',
    'guestMgmt.stayHistory': 'ठहराव इतिहास',
    'guestMgmt.noStays': 'कोई ठहराव उपलब्ध नहीं',
    'guestMgmt.select': 'चुनें',
    'guestMgmt.arrival': 'आगमन',
    'guestMgmt.departure': 'प्रस्थान',
    'guestMgmt.nights': 'रातें',
    'guestMgmt.guestType': 'अतिथि प्रकार',
    'guestMgmt.cureType': 'उपचार प्रकार',
    'guestMgmt.bookingChannel': 'बुकिंग चैनल',
    'guestMgmt.mealPlan': 'भोजन योजना',
    'guestMgmt.roomNumber': 'कमरा नंबर',
    'guestMgmt.roomCategory': 'कमरा श्रेणी',
    'guestMgmt.pricePerNight': 'प्रति रात मूल्य',
    'guestMgmt.totalPrice': 'कुल मूल्य',
    'guestMgmt.spaRevenue': 'स्पा राजस्व',
    'guestMgmt.fbRevenue': 'F&B राजस्व',
    'guestMgmt.otherRevenue': 'अन्य राजस्व',
    'guestMgmt.status': 'स्थिति',
    'guestMgmt.guestList': 'अतिथि सूची',
    'guestMgmt.contact': 'संपर्क',
    'guestMgmt.noGuests': 'कोई अतिथि नहीं मिला',
    'guestMgmt.showing': 'दिखा रहे हैं',
    'guestMgmt.selectGuest': 'अतिथि चुनें',
    'guestMgmt.info': 'जानकारी',
    'guestMgmt.preferences': 'प्राथमिकताएं',
    'guestMgmt.firstVisit': 'पहली यात्रा',
    'guestMgmt.newStayFor': 'नया ठहराव',
    
    // ===== KPI ALARMS VIEW =====
    'kpiAlarm.noThresholdsConfig': 'अभी तक कोई सीमा कॉन्फ़िगर नहीं। "सीमा जोड़ें" पर क्लिक करें।',
    'budgetPlan.title': 'बजट योजना',
    'budgetPlan.description': 'लक्ष्य बनाम वास्तविक तुलना',
    'budgetPlan.noData': 'कोई डेटा उपलब्ध नहीं',
    'budgetPlan.uploadHint': 'बजट की योजना बनाने के लिए अपनी शेष सूची अपलोड करें।',
    'budgetPlan.unsavedChanges': 'सहेजे नहीं गए परिवर्तन',
    'budgetPlan.save': 'सहेजें',
    'budgetPlan.saved': 'बजट सफलतापूर्वक सहेजे गए',
    'budgetPlan.saveError': 'बजट सहेजने में त्रुटि',
    'budgetPlan.totalRevenue': 'कुल राजस्व',
    'budgetPlan.actual': 'वास्तविक',
    'budgetPlan.target': 'लक्ष्य',
    'budgetPlan.db1Total': 'CM I कुल',
    'budgetPlan.db2Total': 'CM II कुल',
    'budgetPlan.deptBudgets': 'विभाग बजट',
    'budgetPlan.department': 'विभाग',
    'budgetPlan.revenueBudget': 'राजस्व बजट',
    'budgetPlan.revenueActual': 'राजस्व वास्तविक',
    'budgetPlan.difference': 'Δ',
    'budgetPlan.cogsBudget': 'COGS बजट',
    'budgetPlan.personnelBudget': 'कर्मचारी बजट',
    'budgetPlan.db1Calculated': 'CM I (गणना)',
    'budgetPlan.db2Calculated': 'CM II (गणना)',
    
    // ===== KPI ALARMS VIEW =====
    'kpiAlarm.title': 'KPI अलार्म और सीमाएं',
    'kpiAlarm.description': 'KPI विचलन पर निगरानी और सूचना',
    'kpiAlarm.noData': 'कोई डेटा उपलब्ध नहीं',
    'kpiAlarm.uploadHint': 'KPI अलार्म कॉन्फ़िगर करने के लिए अपनी शेष सूची अपलोड करें।',
    'kpiAlarm.activeAlarms': 'सक्रिय अलार्म',
    'kpiAlarm.noAlarms': 'सभी KPI सामान्य सीमा में',
    'kpiAlarm.critical': 'गंभीर',
    'kpiAlarm.warning': 'चेतावनी',
    'kpiAlarm.addThreshold': 'सीमा जोड़ें',
    'kpiAlarm.newThreshold': 'नई सीमा',
    'kpiAlarm.department': 'विभाग',
    'kpiAlarm.kpiType': 'KPI प्रकार',
    'kpiAlarm.minThreshold': 'न्यूनतम सीमा',
    'kpiAlarm.maxThreshold': 'अधिकतम सीमा',
    'kpiAlarm.alarmActive': 'अलार्म सक्रिय',
    'kpiAlarm.save': 'सहेजें',
    'kpiAlarm.saved': 'सीमा सहेजी गई',
    'kpiAlarm.deleted': 'सीमा हटाई गई',
    'kpiAlarm.thresholds': 'सीमाएं',
    'kpiAlarm.kpi': 'KPI',
    'kpiAlarm.min': 'न्यूनतम',
    'kpiAlarm.max': 'अधिकतम',
    'kpiAlarm.currentValue': 'वर्तमान मान',
    'kpiAlarm.status': 'स्थिति',
    'kpiAlarm.actions': 'क्रियाएं',
    'kpiAlarm.noDataAvailable': 'कोई डेटा नहीं',
    'kpiAlarm.financeTab': 'वित्त KPIs',
    'kpiAlarm.operationsTab': 'संचालन KPIs',
    'kpiAlarm.exportDoc': 'दस्तावेज़ीकरण',
    
    // ===== GUEST MANAGEMENT =====
    'guests.title': 'अतिथि प्रबंधन',
    'guests.description': 'अतिथि डेटा और ठहराव',
    'guests.guestNumber': 'अतिथि संख्या',
    'guests.name': 'नाम',
    'guests.email': 'ईमेल',
    'guests.phone': 'फ़ोन',
    'guests.stays': 'ठहराव',
    'guests.totalRevenue': 'कुल राजस्व',
    'guests.vip': 'VIP',
    'guests.addGuest': 'नया अतिथि',
    'guests.search': 'अतिथि खोजें...',
    
    // ===== COMMON =====
    'common.loading': 'लोड हो रहा है...',
    'common.save': 'सहेजें',
    'common.cancel': 'रद्द करें',
    'common.delete': 'हटाएं',
    'common.edit': 'संपादित करें',
    'common.add': 'जोड़ें',
    'common.search': 'खोजें',
    'common.filter': 'फ़िल्टर',
    'common.export': 'निर्यात',
    'common.import': 'आयात',
    'common.print': 'प्रिंट',
    'common.close': 'बंद करें',
    'common.confirm': 'पुष्टि करें',
    'common.yes': 'हाँ',
    'common.no': 'नहीं',
    'common.actions': 'कार्रवाई',
    'common.status': 'स्थिति',
    'common.date': 'तिथि',
    'common.time': 'समय',
    'common.total': 'कुल',
    'common.details': 'विवरण',
    'common.back': 'वापस',
    'common.next': 'अगला',
    'common.previous': 'पिछला',
    'common.handbook': 'पुस्तिका',
    'common.language': 'भाषा',
    'common.german': 'Deutsch',
    'common.english': 'English',
    'common.hindi': 'हिन्दी',
    'common.noData': 'कोई डेटा उपलब्ध नहीं',
    'common.error': 'त्रुटि',
    'common.success': 'सफलता',
    
    // ===== MONTHS =====
    'month.january': 'जनवरी',
    'month.february': 'फ़रवरी',
    'month.march': 'मार्च',
    'month.april': 'अप्रैल',
    'month.may': 'मई',
    'month.june': 'जून',
    'month.july': 'जुलाई',
    'month.august': 'अगस्त',
    'month.september': 'सितंबर',
    'month.october': 'अक्टूबर',
    'month.november': 'नवंबर',
    'month.december': 'दिसंबर',
    
    // ===== DAYS =====
    'day.mon': 'सोम',
    'day.tue': 'मंगल',
    'day.wed': 'बुध',
    'day.thu': 'गुरु',
    'day.fri': 'शुक्र',
    'day.sat': 'शनि',
    'day.sun': 'रवि',
    
    // ===== DEPARTMENT KPIs =====
    'deptKpi.title': 'विभाग KPIs',
    'deptKpi.description': 'विभाग के अनुसार योगदान मार्जिन विश्लेषण',
    'deptKpi.noData': 'कोई डेटा उपलब्ध नहीं',
    'deptKpi.uploadHint': 'विभाग KPIs की गणना के लिए अपनी शेष सूची अपलोड करें।',
    'deptKpi.yearComparison': 'वार्षिक तुलना',
    'deptKpi.vs': 'बनाम',
    'deptKpi.operativeDepts': 'परिचालन विभाग',
    'deptKpi.clickForDetails': '(खाता विवरण के लिए क्लिक करें)',
    'deptKpi.serviceDepts': 'सेवा क्षेत्र (लागत अवलोकन)',
    'deptKpi.accountDetails': 'खाता विवरण',
    'deptKpi.accountsWithBalance': 'शेष वाले खाते',
    'deptKpi.noAccountBalances': 'इस अवधि के लिए कोई खाता शेष नहीं',
    'deptKpi.totalRevenue': 'कुल राजस्व',
    'deptKpi.cogs': 'माल की लागत',
    'deptKpi.db1Total': 'योगदान मार्जिन I कुल',
    'deptKpi.personnel': 'कर्मचारी',
    'deptKpi.db2Total': 'योगदान मार्जिन II कुल',
    'deptKpi.energy': 'ऊर्जा',
    'deptKpi.revenue': 'राजस्व',
    'deptKpi.db1': 'CM I',
    'deptKpi.db2': 'CM II',
    'deptKpi.operatingExpenses': 'परिचालन व्यय',
    'deptKpi.marketing': 'विपणन',
    'deptKpi.total': 'कुल',
    'deptKpi.vsLastYear': 'बनाम पिछला वर्ष',
    'deptKpi.py': 'पिव',
    'deptKpi.pyShort': 'पिव',
    'deptKpi.exportSuccess': 'KPI निर्यात सफलतापूर्वक बनाया गया',
    'deptKpi.revenueCurrent': 'वर्तमान राजस्व',
    'deptKpi.revenuePY': 'राजस्व पिव',
    'deptKpi.db2Current': 'CM II वर्तमान',
    'deptKpi.db2PY': 'CM II पिव',
    
    // ===== AREA ANALYSIS VIEW =====
    'areas.title': 'क्षेत्र विश्लेषण',
    'areas.description': 'व्यावसायिक क्षेत्र के अनुसार एकत्रित मूल्य',
    'areas.noData': 'कोई डेटा उपलब्ध नहीं। कृपया शेष सूची अपलोड करें।',
    'areas.revenueByArea': 'क्षेत्र के अनुसार राजस्व',
    'areas.expensesByArea': 'क्षेत्र के अनुसार व्यय',
    'areas.noRevenueData': 'कोई राजस्व डेटा नहीं',
    'areas.noExpenseData': 'कोई व्यय डेटा नहीं',
    
    // ===== COMPARISON VIEW =====
    'comparison.title': 'अवधि तुलना',
    'comparison.description': 'तुलना',
    'comparison.vsPMAndPY': 'बनाम पिछला महीना और पिछला वर्ष',
    'comparison.searchAccount': 'खाता खोजें...',
    'comparison.allAreas': 'सभी क्षेत्र',
    'comparison.allTypes': 'सभी प्रकार',
    'comparison.revenue': 'राजस्व',
    'comparison.expense': 'व्यय',
    'comparison.account': 'खाता',
    'comparison.designation': 'विवरण',
    'comparison.current': 'वर्तमान',
    'comparison.prevMonth': 'पिछला महीना',
    'comparison.pmDiff': 'पिम Δ',
    'comparison.prevYear': 'पिछला वर्ष',
    'comparison.pyDiff': 'पिव Δ',
    'comparison.noData': 'कोई तुलना डेटा नहीं। कृपया कई अवधियां अपलोड करें।',
    'comparison.noDataFiltered': 'इन फ़िल्टर मानदंडों के साथ कोई डेटा नहीं मिला।',
    'comparison.ofPositions': 'में से',
    'comparison.positionsShown': 'स्थितियां दिखाई गईं',
    
    // ===== EXPENSE MODAL =====
    'expense.totalExpenses': 'कुल व्यय',
    'expense.byAccountClass': 'खाता वर्गों (5-8) के अनुसार कुल व्यय का विभाजन',
    'expense.previousMonth': 'पिछला महीना',
    'expense.previousYear': 'पिछला वर्ष',
    'expense.byClass': 'खाता वर्ग के अनुसार व्यय',
    'expense.accountClass': 'खाता वर्ग',
    'expense.current': 'वर्तमान',
    'expense.trendPM': 'रुझान पिम',
    'expense.share': 'हिस्सा',
    'expense.diffPM': 'पिछले महीने से अंतर',
    'expense.diffPY': 'पिछले वर्ष से अंतर',
    
    // ===== BEREICHE (AREAS/DEPARTMENTS) =====
    'area.logis': 'आवास',
    'area.fb': 'एफ&बी',
    'area.rezeption': 'रिसेप्शन',
    'area.spa': 'स्पा',
    'area.aerztin': 'चिकित्सा',
    'area.shop': 'दुकान',
    'area.verwaltung': 'प्रशासन',
    'area.technik': 'तकनीक',
    'area.energie': 'ऊर्जा',
    'area.marketing': 'विपणन',
    'area.personal': 'कर्मचारी',
    'area.finanzierung': 'वित्तपोषण',
    'area.sonstiges': 'अन्य',
    
    // ===== KPI-KATEGORIEN =====
    'kpiCat.erlos': 'राजस्व',
    'kpiCat.wareneinsatz': 'माल की लागत',
    'kpiCat.personal': 'कर्मचारी',
    'kpiCat.betriebsaufwand': 'परिचालन व्यय',
    'kpiCat.energie': 'ऊर्जा',
    'kpiCat.marketing': 'विपणन',
    'kpiCat.abschreibung': 'मूल्यह्रास',
    'kpiCat.zins': 'ब्याज',
    'kpiCat.sonstiges': 'अन्य',
    
    // ===== KOSTENART-TYPEN =====
    'costType.erlos': 'राजस्व',
    'costType.einkauf': 'व्यय',
    'costType.neutral': 'तटस्थ',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('app-language');
    return (saved as Language) || 'de';
  });

  useEffect(() => {
    localStorage.setItem('app-language', language);
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
