// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { Capacitor } from '@capacitor/core';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Detect if running on native mobile platform
const isNativePlatform = Capacitor.isNativePlatform();

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: isNativePlatform ? undefined : localStorage,
    storageKey: 'mandira-kpi-auth',
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: !isNativePlatform,
    flowType: 'pkce',
  }
});